import logging
import time
import asyncio
import queue
import csv
import argparse
import json
import xml.etree.cElementTree as ET
from pathlib import Path
from threading import Thread, Event, Lock

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from scipy.spatial.transform import Rotation

try:
    import cflib.crtp
    from cflib.crazyflie import Crazyflie
    from cflib.crazyflie.log import LogConfig
    import qtm_rt as qtm
    HARDWARE_IMPORT_ERROR = None
except ImportError as exc:
    cflib = None
    Crazyflie = None
    LogConfig = None
    qtm = None
    HARDWARE_IMPORT_ERROR = exc

logging.basicConfig(level=logging.ERROR)

# -----------------------------
# USER SETTINGS
# -----------------------------
QTM_IP = "128.174.245.64"
RATE_HZ = 40
YAW_DEG = 0.0
LAND_TIME = 2.0
FINAL_Z = 0.10

BATTERY_LOG_PERIOD_MS = 200  # 5 Hz battery logging

DEFAULT_PROBLEM_ID = "MA4"
DEFAULT_LLM_TRAJECTORY_JSON = "llm_refined_trajectory.json"
DEFAULT_SPIDERPI_REPLAN_JSON = "llm_spiderpi_replan_trajectory.json"
SPIDERPI_BODY_NAME = "SpiderPi"
SPIDERPI_REPLAN_DISTANCE_M = 0.6
SPIDERPI_MAX_SPEED_M_S = 0.02
SPIDERPI_SAFETY_RADIUS_M = 0.0
SPIDERPI_PREDICTION_HORIZON_S = 20.0
SPIDERPI_REPLAN_LATENCY_BUFFER_S = 20.0
SPIDERPI_Z_OFFSET_M = 0.3
COORDINATE_SCALE = 1.0
COORDINATE_OFFSET = np.array([0.0, 0.0, 0.0], dtype=float)

TRAJ_FIG_NAME = "two_drone_mission_3d_scaled.png"
TRUE_TRAJ_FIG_NAME = "two_drone_mission_3d_original.png"
ERR_FIG_NAME = "two_drone_tracking_error.png"
CSV_LOG_FILES = {
    "cf1": "cf1_trajectory_log.csv",
    "cf2": "cf2_trajectory_log.csv",
}
SPIDERPI_CSV_LOG_FILE = "spiderpi_trajectory_log.csv"

# -----------------------------
# DRONE SETTINGS
# -----------------------------
DRONES_CONFIG = {
    "cf1": {
        "uri": "radio://0/80/2M/E7E7E7E7E7",
        "mocap_name": "Crazyflie",
        "marker_ids": [1, 2, 3, 4],
    },
    "cf2": {
        "uri": "radio://0/80/2M/E7E7E7E7E8",
        "mocap_name": "Crazyflie2",
        "marker_ids": [10, 11, 12, 13],
    }
}

# -----------------------------
# WORKSPACE / OBSTACLES
# -----------------------------
WORKSPACE_X = (-1.0, 2.0)
WORKSPACE_Y = (-1.0, 2.0)
WORKSPACE_Z = (0.0, 1.5)

# Obstacles: (xmin, xmax, ymin, ymax, zmin, zmax)
OBSTACLES = [
    (0.1, 0.4, -0.6, -0.3, 0.0, 0.8),   # O1
    (-0.5, -0.2, 0.6, 0.9, 0.0, 0.8),   # O2
    (0.6, 0.9, 0.1, 0.4, 0.0, 1.2),     # O3
]

# -----------------------------
# REFERENCE WAYPOINT SCHEDULES
# Same start time for both drones
# -----------------------------
MISSION_SCHEDULES = {
    "cf1": [
        (0.0,  np.array([-0.8, -0.8, 0.0])),   # S1
        (2.5,  np.array([-0.8, -0.8, 0.35])),
        (5.0,  np.array([ 0.0, -0.85, 0.55])),
        (8.0,  np.array([ 0.8, -0.75, 0.80])),
        (10.5, np.array([ 1.3, -0.5, 1.0])),   # T1,1
        (12.5, np.array([ 1.3, -0.5, 1.0])),   # hover
        (15.0, np.array([ 1.1,  0.0, 0.95])),
        (18.0, np.array([ 0.4,  0.8, 0.80])),
        (21.0, np.array([-0.2,  1.3, 0.6])),   # T1,2
        (23.0, np.array([-0.2,  1.3, 0.6])),   # hover
        (26.0, np.array([ 0.5,  1.5, 0.8])),
        (29.0, np.array([ 1.2,  1.7, 1.0])),
        (32.0, np.array([ 1.8,  1.8, 1.2])),   # C1
        (34.0, np.array([ 1.8,  1.8, 1.2])),   # hover
    ],
    "cf2": [
        (0.0,  np.array([ 1.8, -0.8, 0.0])),   # S2
        (2.5,  np.array([ 1.8, -0.8, 0.40])),
        (5.0,  np.array([ 1.2, -0.6, 0.75])),
        (8.0,  np.array([ 0.5, -0.45, 1.05])),
        (10.5, np.array([-0.4, -0.2, 1.1])),   # T2,1
        (12.5, np.array([-0.4, -0.2, 1.1])),   # hover
        (15.5, np.array([-0.7,  0.5, 1.05])),
        (18.0, np.array([-0.1,  1.0, 0.95])),
        (21.0, np.array([ 1.2,  1.2, 0.7])),   # T2,2
        (23.0, np.array([ 1.2,  1.2, 0.7])),   # hover
        (26.0, np.array([ 0.8,  1.45, 0.95])),
        (29.0, np.array([ 0.0,  1.7, 1.1])),
        (32.0, np.array([-0.8,  1.8, 1.2])),   # C2
        (34.0, np.array([-0.8,  1.8, 1.2])),   # hover
    ],
}

MISSION_END_TIME = 34.0
TOTAL_END_TIME = MISSION_END_TIME + LAND_TIME

MISSION_POINTS = {
    "cf1": {
        "S1": np.array([-0.8, -0.8, 0.0]),
        "T11": np.array([1.3, -0.5, 1.0]),
        "T12": np.array([-0.2, 1.3, 0.6]),
        "C1": np.array([1.8, 1.8, 1.2]),
    },
    "cf2": {
        "S2": np.array([1.8, -0.8, 0.0]),
        "T21": np.array([-0.4, -0.2, 1.1]),
        "T22": np.array([1.2, 1.2, 0.7]),
        "C2": np.array([-0.8, 1.8, 1.2]),
    }
}


# -----------------------------
# LLM / JSON TRAJECTORY IMPORT
# -----------------------------
def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Run the two-Crazyflie tracker using either the built-in schedule or a "
            "verified trajectory generated by tool_pipeline.py."
        )
    )
    parser.add_argument("--problem-id", default=DEFAULT_PROBLEM_ID)
    parser.add_argument(
        "--trajectory-source",
        choices=["llm", "json", "reference", "built-in"],
        default="llm",
        help=(
            "'llm' runs tool_pipeline.run_llm_refinement first, 'json' loads an existing "
            "trajectory JSON, 'reference' uses the problem's built-in key waypoints, and "
            "'built-in' keeps the legacy schedule inside this file."
        ),
    )
    parser.add_argument(
        "--trajectory-json",
        default=DEFAULT_LLM_TRAJECTORY_JSON,
        help="JSON path to read for --trajectory-source json.",
    )
    parser.add_argument(
        "--trajectory-output",
        default=DEFAULT_LLM_TRAJECTORY_JSON,
        help="JSON path written by --trajectory-source llm/reference and then tracked.",
    )
    parser.add_argument(
        "--reuse-existing-llm-trajectory",
        action="store_true",
        help=(
            "When --trajectory-source llm is used, reuse an existing verified "
            "trajectory JSON at --trajectory-output instead of rerunning refinement."
        ),
    )
    parser.add_argument("--max-refinement-turns", type=int, default=2)
    parser.add_argument("--target-time", type=float, default=None)
    parser.add_argument("--no-nmpc-cbf", action="store_true")
    parser.add_argument("--no-retiming", action="store_true")
    parser.add_argument("--no-planner-plot", action="store_true")
    parser.add_argument(
        "--nmpc-backend",
        choices=["cascade", "full"],
        default="cascade",
    )
    parser.add_argument("--full-apply-steps", type=int, default=4)
    parser.add_argument("--full-max-duration", type=float, default=None)
    parser.add_argument(
        "--allow-unverified",
        action="store_true",
        help="Allow tracking a generated/loaded JSON even when verification.pass is false.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Prepare/load the trajectory and print a summary without connecting to hardware.",
    )
    parser.add_argument(
        "--no-spiderpi-replan",
        dest="no_spiderpi_replan",
        action="store_true",
        help="Disable live SpiderPi proximity-triggered LLM replanning.",
    )
    parser.add_argument(
        "--spiderpi-body-name",
        dest="spiderpi_body_name",
        default=SPIDERPI_BODY_NAME,
        help="Qualisys rigid body name for the SpiderPi moving obstacle.",
    )
    parser.add_argument(
        "--spiderpi-replan-distance",
        dest="spiderpi_replan_distance",
        type=float,
        default=SPIDERPI_REPLAN_DISTANCE_M,
        help="Trigger live replanning when any drone is this close to SpiderPi in scaled/flight XYZ coordinates.",
    )
    parser.add_argument(
        "--spiderpi-z-offset",
        type=float,
        default=SPIDERPI_Z_OFFSET_M,
        help="Added to QTM SpiderPi z before distance/replanning, useful if the rigid body origin is near the base.",
    )
    parser.add_argument(
        "--spiderpi-max-speed",
        dest="spiderpi_max_speed",
        type=float,
        default=SPIDERPI_MAX_SPEED_M_S,
    )
    parser.add_argument(
        "--spiderpi-safety-radius",
        dest="spiderpi_safety_radius",
        type=float,
        default=SPIDERPI_SAFETY_RADIUS_M,
    )
    parser.add_argument(
        "--spiderpi-prediction-horizon",
        dest="spiderpi_prediction_horizon",
        type=float,
        default=SPIDERPI_PREDICTION_HORIZON_S,
        help="Cap on SpiderPi reachability growth used for live replanning.",
    )
    parser.add_argument(
        "--spiderpi-replan-latency-buffer",
        dest="spiderpi_replan_latency_buffer",
        type=float,
        default=SPIDERPI_REPLAN_LATENCY_BUFFER_S,
        help="Extra seconds of SpiderPi motion budget added to the new plan.",
    )
    parser.add_argument(
        "--spiderpi-replan-output",
        dest="spiderpi_replan_output",
        default=DEFAULT_SPIDERPI_REPLAN_JSON,
        help="JSON path written by live SpiderPi-triggered replanning.",
    )
    parser.add_argument(
        "--coordinate-scale",
        type=float,
        default=COORDINATE_SCALE,
        help="Scale from original/planning coordinates to scaled/flight coordinates for plots.",
    )
    parser.add_argument(
        "--coordinate-offset",
        nargs=3,
        type=float,
        default=COORDINATE_OFFSET.tolist(),
        metavar=("X", "Y", "Z"),
        help="Offset added after scaling original/planning coordinates into flight coordinates.",
    )
    parser.add_argument(
        "--no-plan-only-if-qtm-unavailable",
        action="store_true",
        help="Raise an error instead of exiting after planning when QTM/mocap is unavailable.",
    )
    parser.add_argument(
        "--dynamic-start-tolerance",
        type=float,
        default=0.35,
        help="Allowed distance between current drone positions and first replanned waypoints.",
    )
    args = parser.parse_args()
    return args


def _require_hardware_imports():
    if HARDWARE_IMPORT_ERROR is not None:
        raise RuntimeError(
            "Crazyflie/QTM packages could not be imported. Install the hardware "
            f"dependencies or run with --dry-run. Import error: {HARDWARE_IMPORT_ERROR}"
        )


def can_fall_back_to_planning_only(args):
    return not args.no_plan_only_if_qtm_unavailable


def is_qtm_or_mocap_error(exc):
    text = str(exc).lower()
    return "qtm" in text or "mocap" in text or "motion capture" in text


def _as_schedule_waypoint(raw_waypoint, agent_id, index, source_path):
    try:
        t = float(raw_waypoint["t"])
        xyz = np.array(
            [
                float(raw_waypoint["x"]),
                float(raw_waypoint["y"]),
                float(raw_waypoint["z"]),
            ],
            dtype=float,
        )
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(
            f"Invalid waypoint {index} for {agent_id} in {source_path}: {raw_waypoint}"
        ) from exc
    if not np.isfinite(t) or not np.all(np.isfinite(xyz)):
        raise ValueError(
            f"Non-finite waypoint {index} for {agent_id} in {source_path}: {raw_waypoint}"
        )
    return t, xyz


def load_schedules_from_trajectory_json(
    trajectory_path,
    require_verified=True,
):
    path = Path(trajectory_path)
    payload = json.loads(path.read_text(encoding="utf-8"))

    verification = payload.get("verification", {})
    if require_verified and verification.get("pass") is not True:
        reason = verification.get("reason", "verification.pass is not true")
        raise RuntimeError(
            f"Refusing to track unverified trajectory {path}: {reason}. "
            "Use --allow-unverified if this is intentional."
        )

    schedules = {}
    for trajectory in payload.get("agent_trajectories", []):
        agent_id = trajectory.get("agent_id")
        if agent_id not in DRONES_CONFIG:
            raise ValueError(
                f"Trajectory for {agent_id!r} has no matching DRONES_CONFIG entry."
            )
        waypoints = trajectory.get("waypoints", [])
        if not waypoints:
            raise ValueError(f"Trajectory for {agent_id!r} has no waypoints.")

        schedule = [
            _as_schedule_waypoint(raw_waypoint, agent_id, index, path)
            for index, raw_waypoint in enumerate(waypoints)
        ]
        schedule.sort(key=lambda item: item[0])
        for (prev_t, _), (next_t, _) in zip(schedule, schedule[1:]):
            if next_t <= prev_t:
                raise ValueError(
                    f"Trajectory times for {agent_id!r} must be strictly increasing."
                )
        schedules[agent_id] = schedule

    if not schedules:
        raise ValueError(f"No agent_trajectories found in {path}.")
    return schedules, payload


def _problem_workspace_bounds(problem, schedules):
    points = []
    for schedule in schedules.values():
        points.extend([xyz for _, xyz in schedule])
    for obstacle in problem.obstacles:
        points.append(np.array(obstacle.min_corner, dtype=float))
        points.append(np.array(obstacle.max_corner, dtype=float))
    if not points:
        return WORKSPACE_X, WORKSPACE_Y, WORKSPACE_Z

    stacked = np.vstack(points)
    mins = np.min(stacked, axis=0)
    maxs = np.max(stacked, axis=0)
    margin = np.array([0.35, 0.35, 0.20])
    return (
        (float(mins[0] - margin[0]), float(maxs[0] + margin[0])),
        (float(mins[1] - margin[1]), float(maxs[1] + margin[1])),
        (0.0, float(max(1.5, maxs[2] + margin[2]))),
    )


def _mission_points_from_problem(problem, active_agent_ids):
    points = {}
    for agent in problem.agents:
        if agent.agent_id not in active_agent_ids:
            continue
        agent_points = {}
        start = problem.charging_stations[agent.start_station_index]
        agent_points[f"S{agent.start_station_index}"] = np.array(start, dtype=float)
        for target_index in agent.required_target_indices:
            agent_points[f"T{target_index}"] = np.array(
                problem.targets[target_index], dtype=float
            )
        agent_points["G"] = np.array(agent.final_goal, dtype=float)
        points[agent.agent_id] = agent_points
    return points


def configure_problem_context(problem_id, schedules):
    global OBSTACLES, WORKSPACE_X, WORKSPACE_Y, WORKSPACE_Z, MISSION_POINTS

    from problems import get_problem

    problem = get_problem(problem_id)
    OBSTACLES = [
        (
            float(obstacle.min_corner[0]),
            float(obstacle.max_corner[0]),
            float(obstacle.min_corner[1]),
            float(obstacle.max_corner[1]),
            float(obstacle.min_corner[2]),
            float(obstacle.max_corner[2]),
        )
        for obstacle in problem.obstacles
    ]
    WORKSPACE_X, WORKSPACE_Y, WORKSPACE_Z = _problem_workspace_bounds(
        problem, schedules
    )
    MISSION_POINTS = _mission_points_from_problem(problem, set(schedules))


def _generate_llm_trajectory(args):
    from tool_pipeline import run_llm_refinement

    output_path = Path(args.trajectory_output)
    if args.reuse_existing_llm_trajectory and output_path.exists():
        try:
            payload = json.loads(output_path.read_text(encoding="utf-8"))
            if payload.get("problem_id", args.problem_id) != args.problem_id:
                raise ValueError(
                    f"problem_id={payload.get('problem_id')!r} does not match requested {args.problem_id!r}"
                )
            load_schedules_from_trajectory_json(
                output_path,
                require_verified=not args.allow_unverified,
            )
            print(f"[PLAN] Reusing existing trajectory JSON: {output_path}")
            return output_path, payload
        except Exception as exc:
            print(f"[PLAN] Cannot reuse existing trajectory JSON ({exc}); regenerating.")

    print(f"[PLAN] Running LLM tool pipeline for {args.problem_id}...")
    payload = run_llm_refinement(
        output_path=args.trajectory_output,
        problem_id=args.problem_id,
        max_refinement_turns=args.max_refinement_turns,
        use_nmpc_cbf=not args.no_nmpc_cbf,
        use_retiming=not args.no_retiming,
        target_time=args.target_time,
        nmpc_backend=args.nmpc_backend,
        full_apply_steps=args.full_apply_steps,
        full_max_duration=args.full_max_duration,
        estimate_required_time_on_failure=True,
        plot=not args.no_planner_plot,
    )
    return output_path, payload


def spiderpi_effective_position(args, qtm_position):
    position = np.array(qtm_position, dtype=float)
    position[2] += float(args.spiderpi_z_offset)
    return position


def _spiderpi_avoidance_payload(args, spiderpi_position):
    return {
        "label": "SpiderPi",
        "position": [float(v) for v in spiderpi_position],
        "max_speed": float(args.spiderpi_max_speed),
        "safety_radius": float(args.spiderpi_safety_radius),
        "latency_buffer": float(args.spiderpi_replan_latency_buffer),
        "prediction_horizon": float(args.spiderpi_prediction_horizon),
        "sample_dt": 0.25,
    }


def _target_label(target_index):
    return f"T{target_index}"


def _target_index_from_label(label):
    return int(str(label).lstrip("T"))


def _active_target_completion_state(args, mission_time, current_positions):
    from problems import get_problem

    problem = get_problem(args.problem_id)
    completed = {}
    remaining = {}

    for agent in problem.agents:
        schedule = MISSION_SCHEDULES.get(agent.agent_id, [])
        current_position = current_positions.get(agent.agent_id)
        completed_labels = []
        remaining_labels = []

        for target_index in agent.required_target_indices:
            target = np.array(problem.targets[target_index], dtype=float)
            visit_times = [
                t
                for t, waypoint in schedule
                if np.linalg.norm(np.array(waypoint, dtype=float) - target) <= problem.visit_radius
            ]
            if current_position is not None and np.linalg.norm(np.array(current_position, dtype=float) - target) <= problem.visit_radius:
                visit_times.append(float(mission_time))

            label = _target_label(target_index)
            if visit_times and min(visit_times) <= float(mission_time):
                completed_labels.append(label)
            else:
                remaining_labels.append(label)

        completed[agent.agent_id] = completed_labels
        remaining[agent.agent_id] = remaining_labels

    remaining_budget = max(0.0, float(TOTAL_END_TIME) - float(mission_time))
    return completed, remaining, remaining_budget


def _logged_distance_since_start(logger, drone_name, current_position=None):
    _, _, actual_positions, _ = logger.get_arrays(drone_name)
    if len(actual_positions) == 0:
        return 0.0

    points = [np.array(point, dtype=float) for point in actual_positions]
    if current_position is not None:
        current_position = np.array(current_position, dtype=float)
        if np.linalg.norm(points[-1] - current_position) > 1e-6:
            points.append(current_position)

    if len(points) < 2:
        return 0.0

    return float(
        sum(np.linalg.norm(points[index] - points[index - 1]) for index in range(1, len(points)))
    )


def _inside_charge_station(problem, point):
    point = np.array(point, dtype=float)
    return any(
        np.linalg.norm(point - np.array(station, dtype=float)) <= problem.charge_radius
        for station in problem.charging_stations
    )


def _battery_estimate_from_log(args, logger, drone_name, current_position, mission_time=None):
    from problems import get_problem

    problem = get_problem(args.problem_id)
    times, _, actual_positions, _ = logger.get_arrays(drone_name)
    if mission_time is not None:
        cutoff = float(mission_time)
        keep = times < cutoff - 1e-6
        times = times[keep]
        actual_positions = actual_positions[keep]

    points = [np.array(point, dtype=float) for point in actual_positions]
    point_times = [float(t) for t in times]
    if current_position is not None:
        current_position = np.array(current_position, dtype=float)
        if not points or np.linalg.norm(points[-1] - current_position) > 1e-6:
            points.append(current_position)
            point_times.append(
                float(mission_time)
                if mission_time is not None
                else (point_times[-1] if point_times else 0.0)
            )

    distance = 0.0
    charged_amount = 0.0
    estimated_battery = float(problem.battery_start)
    for index in range(1, len(points)):
        segment_distance = float(np.linalg.norm(points[index] - points[index - 1]))
        distance += segment_distance
        estimated_battery -= segment_distance * float(problem.battery_loss_per_meter)
        if _inside_charge_station(problem, points[index - 1]) and _inside_charge_station(problem, points[index]):
            dt = max(0.0, float(point_times[index] - point_times[index - 1]))
            charge = dt * float(problem.charge_rate)
            charged_amount += charge
            estimated_battery += charge
        estimated_battery = min(float(problem.battery_start), max(0.0, estimated_battery))

    return {
        "distance": distance,
        "estimated_battery": estimated_battery,
        "charged_amount": charged_amount,
        "battery_start": float(problem.battery_start),
        "battery_floor": float(problem.battery_floor),
        "loss_per_meter": float(problem.battery_loss_per_meter),
        "charge_rate": float(problem.charge_rate),
    }


def _battery_state_for_replan(args, logger, current_positions, mission_time=None):
    return {
        drone_name: _battery_estimate_from_log(
            args,
            logger,
            drone_name,
            current_positions.get(drone_name),
            mission_time=mission_time,
        )
        for drone_name in current_positions.keys()
    }


def _live_replan_problem_prompt(args, current_positions, spiderpi_position, mission_time, battery_state=None):
    from problems import get_problem

    problem = get_problem(args.problem_id)
    completed_targets, remaining_targets, remaining_budget = _active_target_completion_state(
        args,
        mission_time,
        current_positions,
    )
    current_lines = "\n".join(
        (
            f"- {agent_id}: new_start_position="
            f"[{pos[0]:.3f}, {pos[1]:.3f}, {pos[2]:.3f}]"
        )
        for agent_id, pos in current_positions.items()
    )
    completed_lines = "\n".join(
        f"- {agent_id}: {labels if labels else 'none'}"
        for agent_id, labels in completed_targets.items()
    )
    remaining_lines = "\n".join(
        f"- {agent_id}: {labels if labels else 'none'}"
        for agent_id, labels in remaining_targets.items()
    )
    route_lines = []
    for agent in problem.agents:
        current_pos = current_positions.get(agent.agent_id)
        if current_pos is None:
            continue
        route_parts = [
            f"current_start=[{current_pos[0]:.3f}, {current_pos[1]:.3f}, {current_pos[2]:.3f}]"
        ]
        for target_index in agent.required_target_indices:
            if _target_label(target_index) in remaining_targets.get(agent.agent_id, []):
                target = problem.targets[target_index]
                route_parts.append(
                    f"T{target_index}=[{target[0]:.3f}, {target[1]:.3f}, {target[2]:.3f}]"
                )
        final_goal = agent.final_goal
        route_parts.append(
            f"final_goal=[{final_goal[0]:.3f}, {final_goal[1]:.3f}, {final_goal[2]:.3f}]"
        )
        route_lines.append(f"- {agent.agent_id}: " + " -> ".join(route_parts))
    route_skeleton = "\n".join(route_lines)
    battery_lines = ""
    if battery_state:
        battery_lines = "\n" + "\n".join(
            (
                f"- {agent_id}: estimated_battery={info['estimated_battery']:.1f}%, "
                f"distance_travelled={info['distance']:.2f} m, floor={info['battery_floor']:.1f}%, "
                f"loss_per_meter={info['loss_per_meter']:.1f}%/m, "
                f"logged_charge_gain={info.get('charged_amount', 0.0):.1f}%"
            )
            for agent_id, info in battery_state.items()
        )
    return f"""
LIVE REPLAN MISSION:
This is a fresh mission prompt generated during flight. The current drone position
is the new mission start for replanning. Do not use the original charging-station
start positions at all. Plan only from the current drone positions below, and
include only the remaining targets that still need to be visited. Already
completed targets are already done and must not appear again.

Elapsed mission time at replan trigger: {float(mission_time):.2f} s.
Remaining mission budget for the new plan: {remaining_budget:.2f} s.

Already completed targets that must NOT be revisited:
{completed_lines}

Remaining targets that must still be included:
{remaining_lines}

Required route skeleton for each agent:
{route_skeleton}

If an agent has no remaining targets, go directly from its new start position to the final goal.

If an agent has remaining targets, the replanned route must include every remaining
target listed above in mission order before the final goal. Do not connect the
new start position directly to the final goal when remaining targets are present.

At minimum, include a waypoint at each remaining target position.

The first key_waypoint for each agent must be exactly its current drone position,
and that position replaces the original mission start in both smoothing and verification.

Battery constraint from logged travel distance:{battery_lines}
Keep every drone above its battery floor using the estimated remaining battery.

Current drone positions:
{current_lines}

SpiderPi moving obstacle constraint:
- Current SpiderPi effective position from Qualisys is [{spiderpi_position[0]:.3f}, {spiderpi_position[1]:.3f}, {spiderpi_position[2]:.3f}] m.
- SpiderPi rigid body name in Qualisys is {args.spiderpi_body_name}.
- The SpiderPi robot arm is treated as part of the obstacle; the effective position already includes z_offset={args.spiderpi_z_offset:.2f} m.
- Assume SpiderPi maximum speed is {args.spiderpi_max_speed:.3f} m/s.
- Account for planning latency by reserving at least latency_buffer={args.spiderpi_replan_latency_buffer:.1f} s of SpiderPi motion.
- Compute the reachable danger radius using the maximum speed, for example:
  danger_radius = spiderpi_safety_radius + spiderpi_max_speed * min(t + latency_buffer, prediction_horizon)
- spiderpi_safety_radius={args.spiderpi_safety_radius:.2f} m,
  prediction_horizon={args.spiderpi_prediction_horizon:.1f} s.
- Keep every drone's 3D position outside the SpiderPi reachable danger region at all times.
""".strip()


def run_spiderpi_triggered_replan(args, current_positions, spiderpi_position, mission_time, logger):
    from tool_pipeline import run_llm_refinement

    output_path = Path(args.spiderpi_replan_output)
    start_positions = {
        agent_id: [float(v) for v in position]
        for agent_id, position in current_positions.items()
    }
    spiderpi_avoidance = _spiderpi_avoidance_payload(args, spiderpi_position)
    _, remaining_targets, remaining_budget = _active_target_completion_state(
        args,
        mission_time,
        current_positions,
    )
    battery_state = _battery_state_for_replan(
        args,
        logger,
        current_positions,
        mission_time=mission_time,
    )
    required_target_indices = {
        agent_id: [_target_index_from_label(label) for label in labels]
        for agent_id, labels in remaining_targets.items()
    }
    initial_battery_levels = {
        agent_id: float(info["estimated_battery"])
        for agent_id, info in battery_state.items()
    }
    problem_prompt = _live_replan_problem_prompt(
        args,
        current_positions,
        spiderpi_position,
        mission_time,
        battery_state=battery_state,
    )

    print("[SPIDERPI] Running live LLM replan with SpiderPi reachable-set avoidance...")
    payload = run_llm_refinement(
        output_path=output_path,
        problem_id=args.problem_id,
        max_refinement_turns=args.max_refinement_turns,
        use_nmpc_cbf=not args.no_nmpc_cbf,
        use_retiming=not args.no_retiming,
        target_time=remaining_budget,
        nmpc_backend=args.nmpc_backend,
        full_apply_steps=args.full_apply_steps,
        full_max_duration=args.full_max_duration,
        estimate_required_time_on_failure=True,
        plot=not args.no_planner_plot,
        problem_prompt=problem_prompt,
        dynamic_start_positions=start_positions,
        dynamic_start_tolerance=args.dynamic_start_tolerance,
        dynamic_obstacle_avoidance=spiderpi_avoidance,
        required_target_indices=required_target_indices,
        initial_battery_levels=initial_battery_levels,
    )
    schedules, loaded_payload = load_schedules_from_trajectory_json(
        output_path,
        require_verified=not args.allow_unverified,
    )
    output_path.write_text(json.dumps(loaded_payload, indent=2), encoding="utf-8")
    print(f"[SPIDERPI] Replan completed and saved to: {output_path}")
    return output_path, schedules, loaded_payload


def _generate_reference_trajectory(args):
    from tool_pipeline import save_reference_trajectory

    print(f"[PLAN] Building reference trajectory for {args.problem_id}...")
    payload = save_reference_trajectory(
        output_path=args.trajectory_output,
        problem_id=args.problem_id,
        use_retiming=not args.no_retiming,
        target_time=args.target_time,
    )
    return Path(args.trajectory_output), payload


def prepare_mission(args):
    global MISSION_SCHEDULES, MISSION_END_TIME, TOTAL_END_TIME

    if args.trajectory_source == "built-in":
        active_names = list(MISSION_SCHEDULES.keys())
        print("[PLAN] Using legacy built-in tracking schedule.")
        return active_names, None

    if args.trajectory_source == "llm":
        trajectory_path, payload = _generate_llm_trajectory(args)
    elif args.trajectory_source == "reference":
        trajectory_path, payload = _generate_reference_trajectory(args)
    else:
        trajectory_path = Path(args.trajectory_json)
        payload = None

    schedules, loaded_payload = load_schedules_from_trajectory_json(
        trajectory_path,
        require_verified=not args.allow_unverified,
    )
    payload = loaded_payload if payload is None else payload
    problem_id = payload.get("problem_id", args.problem_id)
    configure_problem_context(problem_id, schedules)

    MISSION_SCHEDULES = schedules
    MISSION_END_TIME = max(schedule[-1][0] for schedule in schedules.values())
    TOTAL_END_TIME = MISSION_END_TIME + LAND_TIME

    verification = payload.get("verification", {})
    print(f"[PLAN] Loaded verified trajectory: {trajectory_path}")
    print(f"[PLAN] Problem: {problem_id}")
    print(f"[PLAN] Pass: {verification.get('pass')}")
    print(f"[PLAN] Reason: {verification.get('reason', '')}")
    print(
        f"[PLAN] Active drones: {', '.join(schedules.keys())}; "
        f"mission end: {MISSION_END_TIME:.2f}s; total with landing: {TOTAL_END_TIME:.2f}s"
    )
    return list(schedules.keys()), trajectory_path


# -----------------------------
# LOGGER
# -----------------------------
class MultiTrajectoryLogger:
    def __init__(self, drone_names):
        self.lock = Lock()
        self.samples = {name: [] for name in drone_names}
        self.spiderpi_samples = []

    def add(self, drone_name, t, ref_xyz, actual_xyz, vbat=None, battery_level=None, pm_state=None):
        with self.lock:
            self.samples[drone_name].append({
                "t": float(t),
                "ref": np.array(ref_xyz, dtype=float),
                "act": np.array(actual_xyz, dtype=float),
                "err": float(np.linalg.norm(np.array(actual_xyz) - np.array(ref_xyz))),
                "vbat": None if vbat is None else float(vbat),
                "battery_level": None if battery_level is None else float(battery_level),
                "pm_state": None if pm_state is None else int(pm_state),
            })

    def add_spiderpi(self, t, xyz):
        with self.lock:
            self.spiderpi_samples.append({
                "t": float(t),
                "pos": np.array(xyz, dtype=float),
            })

    def get_arrays(self, drone_name):
        with self.lock:
            data = self.samples[drone_name]
            if len(data) == 0:
                return (
                    np.zeros((0,)),
                    np.zeros((0, 3)),
                    np.zeros((0, 3)),
                    np.zeros((0,))
                )
            t = np.array([d["t"] for d in data], dtype=float)
            ref = np.vstack([d["ref"] for d in data])
            act = np.vstack([d["act"] for d in data])
            err = np.array([d["err"] for d in data], dtype=float)
            return t, ref, act, err

    def get_spiderpi_arrays(self):
        with self.lock:
            data = self.spiderpi_samples
            if len(data) == 0:
                return np.zeros((0,)), np.zeros((0, 3))
            t = np.array([d["t"] for d in data], dtype=float)
            pos = np.vstack([d["pos"] for d in data])
            return t, pos

    def save_csv(self, drone_name, filename):
        with self.lock:
            data = self.samples[drone_name]

            with open(filename, "w", newline="") as f:
                writer = csv.writer(f)
                writer.writerow([
                    "time",
                    "ref_x", "ref_y", "ref_z",
                    "act_x", "act_y", "act_z",
                    "err",
                    "vbat",
                    "battery_level",
                    "pm_state",
                ])
                for d in data:
                    writer.writerow([
                        d["t"],
                        d["ref"][0], d["ref"][1], d["ref"][2],
                        d["act"][0], d["act"][1], d["act"][2],
                        d["err"],
                        d["vbat"],
                        d["battery_level"],
                        d["pm_state"],
                    ])

        print(f"[CSV] Saved log for {drone_name}: {filename}")

    def save_spiderpi_csv(self, filename):
        with self.lock:
            data = self.spiderpi_samples

            with open(filename, "w", newline="") as f:
                writer = csv.writer(f)
                writer.writerow([
                    "time",
                    "x", "y", "z",
                ])
                for d in data:
                    writer.writerow([
                        d["t"],
                        d["pos"][0], d["pos"][1], d["pos"][2],
                    ])

        print(f"[CSV] Saved log for SpiderPi: {filename}")

    def save_all_csv(self, filename_map):
        for drone_name, filename in filename_map.items():
            self.save_csv(drone_name, filename)


# -----------------------------
# BATTERY MONITOR
# -----------------------------
class BatteryMonitor:
    def __init__(self, cf, name, period_ms=200):
        self.name = name
        self.lock = Lock()
        self.vbat = None
        self.battery_level = None
        self.pm_state = None

        self.logconf = LogConfig(name=f"Battery_{name}", period_in_ms=period_ms)
        self.logconf.add_variable("pm.vbat", "float")
        self.logconf.add_variable("pm.batteryLevel", "uint8_t")
        self.logconf.add_variable("pm.state", "int8_t")

        cf.log.add_config(self.logconf)
        self.logconf.data_received_cb.add_callback(self._data_received)
        self.logconf.error_cb.add_callback(self._error)

    def start(self):
        self.logconf.start()
        print(f"[BAT] Started battery logging: {self.name}")

    def stop(self):
        try:
            self.logconf.stop()
        except Exception:
            pass

    def _data_received(self, timestamp, data, logconf):
        with self.lock:
            self.vbat = data.get("pm.vbat", None)
            self.battery_level = data.get("pm.batteryLevel", None)
            self.pm_state = data.get("pm.state", None)

    def _error(self, logconf, msg):
        print(f"[BAT] Log error on {self.name}: {msg}")

    def get_latest(self):
        with self.lock:
            return self.vbat, self.battery_level, self.pm_state


# -----------------------------
# MOCAP TRANSFORM
# -----------------------------
class MocapTransform:
    def __init__(self, d1=0.0136, d2=0.0109):
        self.d_offset = d1 + d2

    def update_and_transform(self, mocap_position, mocap_euler):
        if not np.all(np.isfinite(mocap_position)) or not np.all(np.isfinite(mocap_euler)):
            return np.full(3, np.nan), np.full(4, np.nan)

        p_cf = np.array(mocap_position, dtype=float)
        p_cf[2] -= self.d_offset

        R_cf = Rotation.from_euler("ZYX", mocap_euler)
        q_cf = R_cf.as_quat()
        return p_cf, q_cf


# -----------------------------
# CRAZYFLIE CLIENT
# -----------------------------
class CrazyflieClient:
    def __init__(self, uri, marker_deck_ids=None):
        self.uri = uri
        self.marker_deck_ids = marker_deck_ids
        self.cf = Crazyflie(rw_cache="./cache")
        self.ready = Event()
        self.battery_monitor = None

        self.cf.fully_connected.add_callback(self._fully_connected)

        print(f"[CF] Connecting to {uri}")
        self.cf.open_link(uri)

    def _fully_connected(self, uri):
        print(f"[CF] Fully connected to {uri}")

        if self.marker_deck_ids:
            self.cf.param.set_value("activeMarker.mode", 3)
            self.cf.param.set_value("activeMarker.front", self.marker_deck_ids[0])
            self.cf.param.set_value("activeMarker.right", self.marker_deck_ids[1])
            self.cf.param.set_value("activeMarker.back", self.marker_deck_ids[2])
            self.cf.param.set_value("activeMarker.left", self.marker_deck_ids[3])

        self.cf.param.set_value("stabilizer.estimator", 2)
        self.cf.param.set_value("stabilizer.controller", 1)
        self.ready.set()

    def setup_battery_monitor(self, name, period_ms=200):
        self.battery_monitor = BatteryMonitor(self.cf, name=name, period_ms=period_ms)
        self.battery_monitor.start()

    def get_battery(self):
        if self.battery_monitor is None:
            return None, None, None
        return self.battery_monitor.get_latest()

    def stop_battery_monitor(self):
        if self.battery_monitor is not None:
            self.battery_monitor.stop()

    def reset_estimator(self):
        self.cf.param.set_value("kalman.resetEstimation", 1)
        time.sleep(0.1)
        self.cf.param.set_value("kalman.resetEstimation", 0)

    def send_position_setpoint(self, xyz, yaw_deg=0.0):
        self.cf.commander.send_position_setpoint(
            float(xyz[0]), float(xyz[1]), float(xyz[2]), float(yaw_deg)
        )


# -----------------------------
# EXTPOSE SENDER
# -----------------------------
def pose_sender(cf_client, pose_queue, stop_event):
    while not stop_event.is_set():
        try:
            pose = pose_queue.get(timeout=0.1)
            cf_client.cf.extpos.send_extpose(*pose)
        except queue.Empty:
            continue


# -----------------------------
# QUALISYS MULTI CLIENT
# -----------------------------
class QualisysMultiClient(Thread):
    def __init__(self, ip_address, body_to_queue_map, tracked_body_names=None):
        super().__init__(daemon=True)
        self.ip_address = ip_address
        self.body_to_queue_map = body_to_queue_map
        self.tracked_body_names = set(tracked_body_names or [])
        self.all_body_names = set(body_to_queue_map.keys()) | self.tracked_body_names
        self.stop_event = Event()
        self.streaming_started = Event()
        self.transforms = {name: MocapTransform() for name in body_to_queue_map.keys()}

        self.latest_pose_lock = Lock()
        self.latest_positions = {name: None for name in self.all_body_names}

        self.start()

    def get_latest_position(self, body_name):
        with self.latest_pose_lock:
            p = self.latest_positions.get(body_name, None)
            if p is None:
                return None
            return np.array(p, dtype=float)

    def run(self):
        asyncio.run(self._life_cycle())

    async def _life_cycle(self):
        connection = await qtm.connect(self.ip_address, version="1.24")
        if connection is None:
            raise RuntimeError("Failed to connect to QTM")

        params = await connection.get_parameters(parameters=["6d"])
        xml = ET.fromstring(params)
        labels = [label.text.strip() for label in xml.findall("*/Body/Name")]
        print(f"[QTM] Bodies: {labels}")

        def on_packet(packet):
            header, bodies = packet.get_6d()
            if bodies is None:
                return

            for body_name in self.all_body_names:
                if body_name not in labels:
                    continue

                idx = labels.index(body_name)
                pos, ori = bodies[idx]

                if np.any(np.isnan(pos)):
                    continue

                raw_position = np.array(pos) / 1e3
                if body_name in self.body_to_queue_map:
                    R = Rotation.from_matrix(np.reshape(ori.matrix, (3, 3), order="F"))
                    yaw, pitch, roll = R.as_euler("ZYX", degrees=False)
                    p_cf, q_cf = self.transforms[body_name].update_and_transform(
                        raw_position,
                        [yaw, pitch, roll]
                    )
                else:
                    p_cf = raw_position
                    q_cf = None

                if np.all(np.isfinite(p_cf)):
                    if body_name in self.body_to_queue_map:
                        self.streaming_started.set()

                    with self.latest_pose_lock:
                        self.latest_positions[body_name] = p_cf.copy()

                    if body_name in self.body_to_queue_map:
                        q = self.body_to_queue_map[body_name]
                        try:
                            if q.full():
                                q.get_nowait()
                            q.put_nowait((*p_cf, *q_cf))
                        except Exception:
                            pass

        await connection.stream_frames(components=["6d"], on_packet=on_packet)

        while not self.stop_event.is_set():
            await asyncio.sleep(0.1)

        await connection.stream_frames_stop()
        connection.disconnect()

    def close(self):
        self.stop_event.set()
        self.join(timeout=1.0)
        if self.is_alive():
            print("[QTM] Close timed out; letting daemon thread exit with the process.")


# -----------------------------
# TRAJECTORY HELPERS
# -----------------------------
def smoothstep(tau):
    tau = np.clip(tau, 0.0, 1.0)
    return 10 * tau**3 - 15 * tau**4 + 6 * tau**5

def interpolate_xyz(p0, p1, tau):
    s = smoothstep(tau)
    return (1.0 - s) * np.array(p0, dtype=float) + s * np.array(p1, dtype=float)

def desired_position_from_schedule(schedule, t_now):
    if t_now <= schedule[0][0]:
        return np.array(schedule[0][1], dtype=float)

    for i in range(len(schedule) - 1):
        t0, p0 = schedule[i]
        t1, p1 = schedule[i + 1]
        if t0 <= t_now <= t1:
            if t1 == t0:
                return np.array(p1, dtype=float)
            tau = (t_now - t0) / (t1 - t0)
            return interpolate_xyz(p0, p1, tau)

    return np.array(schedule[-1][1], dtype=float)

def desired_position_with_landing(drone_name, t_now):
    schedule = MISSION_SCHEDULES[drone_name]

    if t_now <= MISSION_END_TIME:
        return desired_position_from_schedule(schedule, t_now)

    t_land = t_now - MISSION_END_TIME
    p_start = np.array(schedule[-1][1], dtype=float)
    p_end = np.array([p_start[0], p_start[1], FINAL_Z], dtype=float)
    tau = min(t_land / LAND_TIME, 1.0)
    return interpolate_xyz(p_start, p_end, tau)


# -----------------------------
# PLOTTING HELPERS
# -----------------------------
def make_box_faces(xmin, xmax, ymin, ymax, zmin, zmax):
    v = [
        [xmin, ymin, zmin],
        [xmax, ymin, zmin],
        [xmax, ymax, zmin],
        [xmin, ymax, zmin],
        [xmin, ymin, zmax],
        [xmax, ymin, zmax],
        [xmax, ymax, zmax],
        [xmin, ymax, zmax],
    ]
    return [
        [v[0], v[1], v[2], v[3]],
        [v[4], v[5], v[6], v[7]],
        [v[0], v[1], v[5], v[4]],
        [v[2], v[3], v[7], v[6]],
        [v[1], v[2], v[6], v[5]],
        [v[4], v[7], v[3], v[0]],
    ]

def save_3d_mission_figure(logger, filename):
    fig = plt.figure(figsize=(11, 9))
    ax = fig.add_subplot(111, projection="3d")

    transform = lambda p: np.array(p, dtype=float)

    for k, obs in enumerate(OBSTACLES, start=1):
        corners = [
            transform([obs[x_i], obs[y_i], obs[z_i]])
            for x_i in (0, 1)
            for y_i in (2, 3)
            for z_i in (4, 5)
        ]
        mins = np.min(np.vstack(corners), axis=0)
        maxs = np.max(np.vstack(corners), axis=0)
        transformed_obs = (
            mins[0], maxs[0],
            mins[1], maxs[1],
            mins[2], maxs[2],
        )
        faces = make_box_faces(*transformed_obs)
        box = Poly3DCollection(faces, alpha=0.30)
        box.set_edgecolor("k")
        ax.add_collection3d(box)

        cx = 0.5 * (transformed_obs[0] + transformed_obs[1])
        cy = 0.5 * (transformed_obs[2] + transformed_obs[3])
        cz = transformed_obs[5]
        ax.text(cx, cy, cz + 0.03, f"O{k}")

    for drone_name in logger.samples.keys():
        _, ref, act, _ = logger.get_arrays(drone_name)

        if len(ref) > 0:
            ref = np.vstack([transform(point) for point in ref])
            ax.plot(ref[:, 0], ref[:, 1], ref[:, 2], "--", linewidth=2, label=f"{drone_name} ref")

        if len(act) > 0:
            act = np.vstack([transform(point) for point in act])
            ax.plot(act[:, 0], act[:, 1], act[:, 2], linewidth=2, label=f"{drone_name} actual")

    for drone_name, pts in MISSION_POINTS.items():
        for label, p in pts.items():
            p = transform(p)
            ax.scatter(p[0], p[1], p[2], s=60)
            ax.text(p[0], p[1], p[2] + 0.04, label)

    _, spiderpi = logger.get_spiderpi_arrays()
    if len(spiderpi) > 0:
        spiderpi = np.vstack([transform(point) for point in spiderpi])
        ax.plot(
            spiderpi[:, 0],
            spiderpi[:, 1],
            spiderpi[:, 2],
            color="black",
            linewidth=2,
            label="SpiderPi",
        )

    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_zlabel("z [m]")
    ax.set_title("Two-Crazyflie Mission: Reference vs Actual Trajectories")
    ax.set_xlim(WORKSPACE_X)
    ax.set_ylim(WORKSPACE_Y)
    ax.set_zlim(WORKSPACE_Z)
    ax.set_box_aspect((
        WORKSPACE_X[1] - WORKSPACE_X[0],
        WORKSPACE_Y[1] - WORKSPACE_Y[0],
        WORKSPACE_Z[1] - WORKSPACE_Z[0]
    ))
    ax.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    plt.close(fig)
    print(f"[PLOT] Saved 3D mission figure: {filename}")


def scaled_to_original(args, point):
    scale = float(args.coordinate_scale)
    if abs(scale) <= 1e-12:
        return np.array(point, dtype=float)
    offset = np.array(args.coordinate_offset, dtype=float)
    return (np.array(point, dtype=float) - offset) / scale


def save_3d_mission_figure_with_transform(logger, filename, transform, title, args=None):
    fig = plt.figure(figsize=(11, 9))
    ax = fig.add_subplot(111, projection="3d")

    transformed_workspace_points = []
    for k, obs in enumerate(OBSTACLES, start=1):
        corners = [
            transform([obs[x_i], obs[y_i], obs[z_i]])
            for x_i in (0, 1)
            for y_i in (2, 3)
            for z_i in (4, 5)
        ]
        corners = np.vstack(corners)
        mins = np.min(corners, axis=0)
        maxs = np.max(corners, axis=0)
        transformed_workspace_points.extend([mins, maxs])
        transformed_obs = (
            mins[0], maxs[0],
            mins[1], maxs[1],
            mins[2], maxs[2],
        )
        box = Poly3DCollection(make_box_faces(*transformed_obs), alpha=0.30)
        box.set_edgecolor("k")
        ax.add_collection3d(box)
        ax.text(
            0.5 * (transformed_obs[0] + transformed_obs[1]),
            0.5 * (transformed_obs[2] + transformed_obs[3]),
            transformed_obs[5] + 0.03,
            f"O{k}",
        )

    for drone_name in logger.samples.keys():
        _, ref, act, _ = logger.get_arrays(drone_name)
        if len(ref) > 0:
            ref = np.vstack([transform(point) for point in ref])
            transformed_workspace_points.extend(ref)
            ax.plot(ref[:, 0], ref[:, 1], ref[:, 2], "--", linewidth=2, label=f"{drone_name} ref")
        if len(act) > 0:
            act = np.vstack([transform(point) for point in act])
            transformed_workspace_points.extend(act)
            ax.plot(act[:, 0], act[:, 1], act[:, 2], linewidth=2, label=f"{drone_name} actual")

    for drone_name, pts in MISSION_POINTS.items():
        for label, p in pts.items():
            p = transform(p)
            transformed_workspace_points.append(p)
            ax.scatter(p[0], p[1], p[2], s=60)
            ax.text(p[0], p[1], p[2] + 0.04, label)

    # get raw spiderpi samples (untransformed) and plot transformed trajectory
    raw_t, raw_spiderpi = logger.get_spiderpi_arrays()
    if len(raw_spiderpi) > 0:
        spiderpi = np.vstack([transform(point) for point in raw_spiderpi])
        transformed_workspace_points.extend(spiderpi)
        ax.plot(
            spiderpi[:, 0],
            spiderpi[:, 1],
            spiderpi[:, 2],
            color="black",
            linewidth=2,
            label="SpiderPi",
        )

        # Draw a safety / reachable sphere around the last SpiderPi position
        try:
            center = spiderpi[-1]
            # compute conservative radius from args if available, else use defaults
            if args is not None:
                payload = _spiderpi_avoidance_payload(args, raw_spiderpi[-1])
                safety = float(payload.get("safety_radius", SPIDERPI_SAFETY_RADIUS_M))
                max_speed = float(payload.get("max_speed", SPIDERPI_MAX_SPEED_M_S))
                latency = float(payload.get("latency_buffer", 0.0))
                pred_horizon = float(payload.get("prediction_horizon", SPIDERPI_PREDICTION_HORIZON_S))
                # Match verifier: use safety radius + max_speed * prediction_horizon
                # (verifier clamps reach_time to prediction_horizon when computing reach_radius)
                radius = safety + max_speed * pred_horizon
            else:
                radius = SPIDERPI_SAFETY_RADIUS_M + SPIDERPI_MAX_SPEED_M_S * SPIDERPI_PREDICTION_HORIZON_S

            u = np.linspace(0, 2 * np.pi, 40)
            v = np.linspace(0, np.pi, 20)
            U, V = np.meshgrid(u, v)
            X = center[0] + radius * np.cos(U) * np.sin(V)
            Y = center[1] + radius * np.sin(U) * np.sin(V)
            Z = center[2] + radius * np.cos(V)
            ax.plot_surface(X, Y, Z, color="red", alpha=0.25, linewidth=0)
        except Exception as e:
            print(f"[PLOT] Could not draw SpiderPi safety sphere: {e}")

    if transformed_workspace_points:
        points = np.vstack(transformed_workspace_points)
        mins = np.min(points, axis=0)
        maxs = np.max(points, axis=0)
        margin = np.array([0.15, 0.15, 0.10])
        ax.set_xlim(float(mins[0] - margin[0]), float(maxs[0] + margin[0]))
        ax.set_ylim(float(mins[1] - margin[1]), float(maxs[1] + margin[1]))
        ax.set_zlim(float(max(0.0, mins[2] - margin[2])), float(maxs[2] + margin[2]))
        ax.set_box_aspect(np.maximum(maxs - mins, 0.1))

    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_zlabel("z [m]")
    ax.set_title(title)
    ax.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    plt.close(fig)
    print(f"[PLOT] Saved 3D mission figure: {filename}")


def save_scaled_and_original_3d_figures(logger, args):
    save_3d_mission_figure_with_transform(
        logger,
        TRAJ_FIG_NAME,
        lambda point: np.array(point, dtype=float),
        "Two-Crazyflie Mission: Scaled Flight Coordinates",
        args,
    )
    save_3d_mission_figure_with_transform(
        logger,
        TRUE_TRAJ_FIG_NAME,
        lambda point: scaled_to_original(args, point),
        "Two-Crazyflie Mission: Original Planning Coordinates",
        args,
    )

def save_tracking_error_figure(logger, filename):
    fig = plt.figure(figsize=(10, 5))
    ax = fig.add_subplot(111)

    for drone_name in logger.samples.keys():
        t, _, _, err = logger.get_arrays(drone_name)
        if len(t) > 0:
            ax.plot(t, err, linewidth=1.5, label=f"{drone_name} error")

    ax.set_xlabel("time [s]")
    ax.set_ylabel("position error [m]")
    ax.set_title("Tracking Error")
    ax.grid(True)
    ax.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    plt.close(fig)
    print(f"[PLOT] Saved tracking error figure: {filename}")


def current_drone_positions(active_drone_names, qtm_client):
    positions = {}
    for drone_name in active_drone_names:
        mocap_name = DRONES_CONFIG[drone_name]["mocap_name"]
        position = qtm_client.get_latest_position(mocap_name)
        if position is None:
            return None
        positions[drone_name] = position
    return positions


def spiderpi_drone_proximity(active_drone_names, qtm_client, args):
    raw_spiderpi_position = qtm_client.get_latest_position(args.spiderpi_body_name)
    if raw_spiderpi_position is None:
        return False, None, None, None

    spiderpi_position = spiderpi_effective_position(args, raw_spiderpi_position)
    min_distance = None
    nearest_drone = None
    for drone_name in active_drone_names:
        mocap_name = DRONES_CONFIG[drone_name]["mocap_name"]
        drone_position = qtm_client.get_latest_position(mocap_name)
        if drone_position is None:
            continue
        distance = float(np.linalg.norm(drone_position - spiderpi_position))
        if min_distance is None or distance < min_distance:
            min_distance = distance
            nearest_drone = drone_name

    if min_distance is None:
        return False, spiderpi_position, None, None
    return (
        min_distance <= args.spiderpi_replan_distance,
        spiderpi_position,
        nearest_drone,
        min_distance,
    )


def start_spiderpi_replan_worker(args, active_drone_names, qtm_client, state, mission_time, logger):
    raw_spiderpi_position = qtm_client.get_latest_position(args.spiderpi_body_name)
    if raw_spiderpi_position is None:
        print("[SPIDERPI] Proximity trigger fired, but SpiderPi position is unavailable.")
        return False
    spiderpi_position = spiderpi_effective_position(args, raw_spiderpi_position)

    drone_positions = current_drone_positions(active_drone_names, qtm_client)
    if drone_positions is None:
        print("[SPIDERPI] Proximity trigger fired, but one or more drone positions are unavailable.")
        return False

    state["done"].clear()
    state["result"] = None
    state["error"] = None
    state["pause_started"] = time.time()
    state["hold_positions"] = {
        drone_name: np.array(position, dtype=float)
        for drone_name, position in drone_positions.items()
    }
    state["trigger_time"] = float(mission_time)
    state["active"] = True

    def worker():
        try:
            state["result"] = run_spiderpi_triggered_replan(
                args,
                drone_positions,
                spiderpi_position,
                mission_time,
                logger,
            )
        except Exception as exc:
            state["error"] = exc
        finally:
            state["done"].set()

    thread = Thread(target=worker, daemon=True)
    state["thread"] = thread
    thread.start()
    print(
        "[SPIDERPI] SpiderPi is within the drone proximity threshold. Holding current positions while "
        "the LLM replans."
    )
    return True


def finish_spiderpi_replan_if_ready(args, state):
    global MISSION_SCHEDULES, MISSION_END_TIME, TOTAL_END_TIME

    if not state.get("active") or not state["done"].is_set():
        return None

    state["active"] = False
    if state.get("thread") is not None:
        state["thread"].join(timeout=1.0)

    if state.get("error") is not None:
        print(f"[SPIDERPI] Live replan failed: {state['error']}")
        return None

    output_path, schedules, payload = state["result"]
    pause_started = state.get("pause_started")
    if pause_started is None:
        pause_started = time.time()
    pause_duration = max(0.0, time.time() - pause_started)
    trigger_time = float(state.get("trigger_time", 0.0))
    live_schedules = {
        agent_id: [
            (float(t) + trigger_time, np.array(xyz, dtype=float))
            for t, xyz in schedule
        ]
        for agent_id, schedule in schedules.items()
    }
    problem_id = payload.get("problem_id", args.problem_id)
    configure_problem_context(problem_id, live_schedules)
    MISSION_SCHEDULES = live_schedules
    MISSION_END_TIME = max(schedule[-1][0] for schedule in live_schedules.values())
    TOTAL_END_TIME = MISSION_END_TIME + LAND_TIME

    verification = payload.get("verification", {})
    print(f"[SPIDERPI] Live replan accepted: {output_path}")
    print("[SPIDERPI] Replanned mission is now active.")
    print(f"[SPIDERPI] Pass: {verification.get('pass')}")
    print(f"[SPIDERPI] Reason: {verification.get('reason', '')}")
    print(f"[SPIDERPI] New mission end: {MISSION_END_TIME:.2f}s")
    print(f"[SPIDERPI] Paused mission clock for {pause_duration:.2f}s while replanning.")
    state["pause_started"] = None
    return pause_duration


# -----------------------------
# MAIN
# -----------------------------
if __name__ == "__main__":
    args = parse_args()
    active_drone_names, trajectory_path = prepare_mission(args)

    if args.dry_run:
        print("[DRY-RUN] Trajectory prepared. Hardware connection skipped.")
        raise SystemExit(0)

    if HARDWARE_IMPORT_ERROR is not None and can_fall_back_to_planning_only(args):
        print(
            "[PLAN-ONLY] Hardware dependencies are unavailable, so only the final "
            f"planned trajectory was prepared. Import error: {HARDWARE_IMPORT_ERROR}"
        )
        raise SystemExit(0)

    _require_hardware_imports()
    cflib.crtp.init_drivers()

    clients = {}
    queues = {}
    pose_stop_event = Event()
    pose_threads = []
    qtm_client = None
    logger = MultiTrajectoryLogger(active_drone_names)
    planning_only_due_to_qtm = False

    try:
        # 1) Connect to both drones
        for name in active_drone_names:
            conf = DRONES_CONFIG[name]
            client = CrazyflieClient(conf["uri"], marker_deck_ids=conf["marker_ids"])
            if not client.ready.wait(timeout=20):
                raise TimeoutError(f"{name} connection timeout")

            # Start battery logging after connection/TOC download
            client.setup_battery_monitor(name=name, period_ms=BATTERY_LOG_PERIOD_MS)

            q = queue.Queue(maxsize=1)
            th = Thread(target=pose_sender, args=(client, q, pose_stop_event), daemon=True)
            th.start()

            clients[name] = client
            queues[name] = q
            pose_threads.append(th)

        # 2) Connect to QTM
        body_to_queue_map = {
            DRONES_CONFIG[name]["mocap_name"]: queues[name]
            for name in active_drone_names
        }
        tracked_body_names = []
        tracked_body_names.append(args.spiderpi_body_name)

        qtm_client = QualisysMultiClient(
            QTM_IP,
            body_to_queue_map,
            tracked_body_names=tracked_body_names,
        )

        print("[MAIN] Waiting for QTM stream...")
        if not qtm_client.streaming_started.wait(timeout=10):
            raise TimeoutError("QTM stream timeout")

        print("[MAIN] Warm-up extpose...")
        time.sleep(2.0)

        # 3) Reset estimators
        for name, client in clients.items():
            print(f"[MAIN] Reset estimator: {name}")
            client.reset_estimator()

        time.sleep(2.0)

        # 4) Arm
        for name, client in clients.items():
            print(f"[MAIN] Arming: {name}")
            client.cf.platform.send_arming_request(True)

        time.sleep(1.0)

        # 5) Main synchronized mission loop
        print("[MISSION] Starting synchronized two-drone mission")
        mission_start_wall = time.time()
        paused_total = 0.0
        dt_cmd = 1.0 / RATE_HZ
        spiderpi_close_prev = False
        spiderpi_replan_state = {
            "active": False,
            "done": Event(),
            "thread": None,
            "result": None,
            "error": None,
            "hold_positions": {},
        }
        spiderpi_replan_state["done"].set()

        while True:
            paused_increment = finish_spiderpi_replan_if_ready(args, spiderpi_replan_state)
            if paused_increment is not None:
                paused_total += paused_increment

            if spiderpi_replan_state["active"] and spiderpi_replan_state.get("pause_started") is not None:
                t_now = spiderpi_replan_state["pause_started"] - mission_start_wall - paused_total
            else:
                t_now = time.time() - mission_start_wall - paused_total
            if t_now > TOTAL_END_TIME:
                break

            spiderpi_close_now = False
            if not args.no_spiderpi_replan:
                (
                    spiderpi_close_now,
                    _spiderpi_position,
                    nearest_drone,
                    min_distance,
                ) = spiderpi_drone_proximity(active_drone_names, qtm_client, args)
                if (
                    spiderpi_close_now
                    and not spiderpi_close_prev
                    and not spiderpi_replan_state["active"]
                ):
                    print(
                        f"[SPIDERPI] Nearest drone: {nearest_drone}; "
                        f"distance={min_distance:.3f} m "
                        f"(xyz, threshold={args.spiderpi_replan_distance:.3f} m)"
                    )
                    start_spiderpi_replan_worker(
                        args,
                        active_drone_names,
                        qtm_client,
                        spiderpi_replan_state,
                        t_now,
                        logger,
                    )
            if qtm_client is not None:
                spiderpi_position = qtm_client.get_latest_position(args.spiderpi_body_name)
                if spiderpi_position is not None:
                    logger.add_spiderpi(t_now, spiderpi_position)
            spiderpi_close_prev = spiderpi_close_now

            for drone_name, client in clients.items():
                if spiderpi_replan_state["active"]:
                    ref_xyz = spiderpi_replan_state["hold_positions"].get(
                        drone_name,
                        desired_position_with_landing(drone_name, t_now),
                    )
                    cmd_xyz = np.array(ref_xyz, dtype=float)
                else:
                    ref_xyz = desired_position_with_landing(drone_name, t_now)
                    cmd_xyz = np.array(ref_xyz, dtype=float)
                client.send_position_setpoint(cmd_xyz, YAW_DEG)

                mocap_name = DRONES_CONFIG[drone_name]["mocap_name"]
                actual_xyz = qtm_client.get_latest_position(mocap_name)
                vbat, battery_level, pm_state = client.get_battery()

                if actual_xyz is not None:
                    logger.add(
                        drone_name=drone_name,
                        t=t_now,
                        ref_xyz=cmd_xyz,
                        actual_xyz=actual_xyz,
                        vbat=vbat,
                        battery_level=battery_level,
                        pm_state=pm_state,
                    )

            time.sleep(dt_cmd)

        print("[MISSION] Mission complete")

    except Exception as e:
        if is_qtm_or_mocap_error(e) and can_fall_back_to_planning_only(args):
            planning_only_due_to_qtm = True
            print(
                "[PLAN-ONLY] QTM/motion capture is unavailable, so the code stopped "
                "after preparing the final planned trajectory."
            )
            print(f"[PLAN-ONLY] Reason: {e}")
        else:
            print(f"[ERROR] {e}")

    finally:
        pose_stop_event.set()

        for client in clients.values():
            try:
                client.stop_battery_monitor()
            except Exception:
                pass

        for client in clients.values():
            try:
                client.cf.commander.send_stop_setpoint()
                time.sleep(0.05)
                client.cf.close_link()
            except Exception:
                pass

        if qtm_client is not None:
            try:
                qtm_client.close()
            except Exception:
                pass

        for th in pose_threads:
            th.join(timeout=1.0)

        try:
            if not planning_only_due_to_qtm:
                save_scaled_and_original_3d_figures(logger, args)
                save_tracking_error_figure(logger, ERR_FIG_NAME)
                logger.save_all_csv(
                    {
                        drone_name: CSV_LOG_FILES.get(
                            drone_name, f"{drone_name}_trajectory_log.csv"
                        )
                        for drone_name in active_drone_names
                    }
                )
                logger.save_spiderpi_csv(SPIDERPI_CSV_LOG_FILE)
        except Exception as e:
            print(f"[PLOT/CSV ERROR] {e}")

        print("[MAIN] Done.")
